FROM node:18-alpine
WORKDIR /app

# Копируем package.json
COPY package*.json ./
COPY packages/database/package.json ./packages/database/

# Устанавливаем зависимости
RUN npm install

# Копируем исходный код
COPY . .

# Создаем папку для логов
RUN mkdir -p logs

# Запускаем сервер
CMD ["npx", "nodemon", "src/server/index.js"]